### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by ZanottiMatteo** [ZanottiMatteo/BGTransports#2]
Sviluppo project plan
il file si trova nella seguente path: Repository > Documentazione > ProjectPlan_v2.0.pdf
@RiccardoMaffeis
@silviabonfanti 
@garganti

**Comment by garganti** [comment]
quando volete che lo gaurdi assegnatemelo, aggiungetemi nel team prima, mi è scaduto l'invito penso

**Comment by ZanottiMatteo** [comment]
Buonasera,
Le ho inviato di nuovo l'invito alla repository.
Distinti saluti

Il ven 15 nov 2024, 17:05 Angelo Gargantini ***@***.***> ha
scritto:

**Comment by ZanottiMatteo** [comment]
@garganti Buonasera, le abbiamo assegnato il project plan

**Comment by garganti** [comment]
Ok va bene. E' un po' generico su quello che deve fare. All'inizio pensavo più rivolto agli utenti, poi ho letto "gestione dei mezzi e dei luoghi di deposito di essi" e sembrava quasi rivolto alle aziende di trasporto. Cercato di chiarirlo nei requisiti.
